#############
### INPUT ###
#############

# https://wiki.hypr.land/Configuring/Variables/#input
input {
    kb_layout = latam
    kb_variant =
    kb_model =
    kb_options =
    kb_rules =

    follow_mouse = 1

    accel_profile = flat
    sensitivity = 1 # -1.0 - 1.0, 0 means no modification.
    force_no_accel = false

    touchpad {
	natural_scroll = true          # Desplazamiento natural
        tap-to-click = true            # Tocar para hacer clic
        disable_while_typing = true    # Desactivar mientras escribes
        #middle_button_emulation = true # Botón medio con 3 dedos
        clickfinger_behavior = false   # Comportamiento de clic con dedos
        #scroll_factor = 0.6            # Factor de desplazamiento (ajusta velocidad)
    }
}

device {
    name = "synps/2-synaptics-touchpad"
    accel_profile = flat
    sensitivity = 0.6
    scroll_factor = 0.8
}

device {
    name = "tpps/2-elan-trackpoint"
    accel_profile = flat
    sensitivity = 0.4
}


# See https://wiki.hypr.land/Configuring/Gestures
gesture = 4, horizontal, workspace
#gesture_threshold = 5

# Cursor
cursor {
    no_hardware_cursors = true
    use_cpu_buffer = true
}

# Example per-device config
# See https://wiki.hypr.land/Configuring/Keywords/#per-device-input-configs for more
device {
    name = epic-mouse-v1
    sensitivity = -0.5
}
