###################
### MY PROGRAMS ###
###################

$terminal = kitty
$fileManager = thunar
$menu = leviathan-launcher
$calendar = leviathan-calendar
$powermenu = leviathan-power-menu
$browser = DRI_PRIME=0 librewolf
$editor = nvim
