# Theme Configuration
# Format: theme_name|hyprland_colors_file|gtk_theme|icon_theme

dracula|Dracula.conf|Dracula|Dracula
catppuccin-mocha|Catppuccin.conf|Catppuccin-Dark|Catppuccin-Mocha
tokyonight|TokyoNight.conf|Tokyonight-Dark|Tokyonight-Dark
everforest-dark|Everforest.conf|Everforest-Dark|Everforest-Dark
rose-pine|RosePine.conf|Rosepine-Dark|Rose-Pine-Moon
material|Material.conf|Material-Dark-Palenight|Material-DeepOcean
nightfox-dusk|NightFox.conf|Nightfox-Dark-Duskfox|NightFox-Dusk
kanagawa|Kanagawa.conf|Kanagawa-Dark-Dragon|Kanagawa
gruvbox|Gruvbox.conf|Gruvbox-Dark|Gruvbox-Dark
nord|Nord.conf|Nordic|Nordzy
eldritch|Eldritch.conf|Eldritch-Dark|Eldritch
